# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\edins\Documents\1 PROYECTOS VUE3 - LARAVEL - INERTIA\seacorp_escritorio\View\modal_inicio.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Modal_Inicio(object):
    def setupUi(self, Modal_Inicio):
        Modal_Inicio.setObjectName("Modal_Inicio")
        Modal_Inicio.resize(1600, 900)
        self.centralwidget = QtWidgets.QWidget(Modal_Inicio)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(190, 150, 1220, 600))
        self.frame.setStyleSheet("#frame{\n"
"    background-color: rgba(255, 255, 255, 140);\n"
"    border-radius: 30px;\n"
"    border: none;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frameBtnReestablecer = QtWidgets.QFrame(self.frame)
        self.frameBtnReestablecer.setGeometry(QtCore.QRect(80, 370, 300, 100))
        self.frameBtnReestablecer.setStyleSheet("#frameBtnReestablecer{\n"
"background-color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 200);\n"
"border-radius: 10px;\n"
"border: none;\n"
"}")
        self.frameBtnReestablecer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBtnReestablecer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBtnReestablecer.setObjectName("frameBtnReestablecer")
        self.lblPresionarReestablecer = QtWidgets.QLabel(self.frameBtnReestablecer)
        self.lblPresionarReestablecer.setGeometry(QtCore.QRect(2, 66, 296, 32))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblPresionarReestablecer.setFont(font)
        self.lblPresionarReestablecer.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblPresionarReestablecer.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;")
        self.lblPresionarReestablecer.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPresionarReestablecer.setObjectName("lblPresionarReestablecer")
        self.lblImgReestablecer = QtWidgets.QLabel(self.frameBtnReestablecer)
        self.lblImgReestablecer.setGeometry(QtCore.QRect(40, 18, 35, 30))
        self.lblImgReestablecer.setStyleSheet("background-color: transparent;")
        self.lblImgReestablecer.setText("")
        self.lblImgReestablecer.setScaledContents(True)
        self.lblImgReestablecer.setObjectName("lblImgReestablecer")
        self.lblReestablecer = QtWidgets.QLabel(self.frameBtnReestablecer)
        self.lblReestablecer.setGeometry(QtCore.QRect(2, 2, 296, 64))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblReestablecer.setFont(font)
        self.lblReestablecer.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblReestablecer.setAutoFillBackground(False)
        self.lblReestablecer.setStyleSheet("background-color: #0055FF;\n"
"color: rgb(255, 255, 255);\n"
"border: none;\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"padding-left: 30px;")
        self.lblReestablecer.setAlignment(QtCore.Qt.AlignCenter)
        self.lblReestablecer.setObjectName("lblReestablecer")
        self.lblPresionarReestablecer.raise_()
        self.lblReestablecer.raise_()
        self.lblImgReestablecer.raise_()
        self.framebtnIniciarProceso = QtWidgets.QFrame(self.frame)
        self.framebtnIniciarProceso.setGeometry(QtCore.QRect(840, 370, 300, 100))
        self.framebtnIniciarProceso.setStyleSheet("#framebtnIniciarProceso{\n"
"background-color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 200);\n"
"border-radius: 10px;\n"
"border: none;\n"
"}")
        self.framebtnIniciarProceso.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framebtnIniciarProceso.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framebtnIniciarProceso.setObjectName("framebtnIniciarProceso")
        self.btnIniciarProceso = QtWidgets.QPushButton(self.framebtnIniciarProceso)
        self.btnIniciarProceso.setGeometry(QtCore.QRect(2, 2, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnIniciarProceso.setFont(font)
        self.btnIniciarProceso.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnIniciarProceso.setAutoFillBackground(False)
        self.btnIniciarProceso.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4683FF;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0649D1;\n"
"}")
        self.btnIniciarProceso.setText("")
        self.btnIniciarProceso.setObjectName("btnIniciarProceso")
        self.lblPresionarIniciarProceso = QtWidgets.QLabel(self.framebtnIniciarProceso)
        self.lblPresionarIniciarProceso.setGeometry(QtCore.QRect(0, 66, 296, 32))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblPresionarIniciarProceso.setFont(font)
        self.lblPresionarIniciarProceso.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblPresionarIniciarProceso.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;")
        self.lblPresionarIniciarProceso.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPresionarIniciarProceso.setObjectName("lblPresionarIniciarProceso")
        self.lblImgIniciarProceso = QtWidgets.QLabel(self.framebtnIniciarProceso)
        self.lblImgIniciarProceso.setGeometry(QtCore.QRect(20, 15, 60, 35))
        self.lblImgIniciarProceso.setStyleSheet("background-color: transparent;")
        self.lblImgIniciarProceso.setText("")
        self.lblImgIniciarProceso.setScaledContents(True)
        self.lblImgIniciarProceso.setObjectName("lblImgIniciarProceso")
        self.lblIniciarProceso = QtWidgets.QLabel(self.framebtnIniciarProceso)
        self.lblIniciarProceso.setGeometry(QtCore.QRect(2, 2, 296, 64))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblIniciarProceso.setFont(font)
        self.lblIniciarProceso.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblIniciarProceso.setAutoFillBackground(False)
        self.lblIniciarProceso.setStyleSheet("background-color: #0055FF;\n"
"color: rgb(255, 255, 255);\n"
"border: none;\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"padding-left: 50px;")
        self.lblIniciarProceso.setAlignment(QtCore.Qt.AlignCenter)
        self.lblIniciarProceso.setObjectName("lblIniciarProceso")
        self.btnIniciarProceso.raise_()
        self.lblPresionarIniciarProceso.raise_()
        self.lblIniciarProceso.raise_()
        self.lblImgIniciarProceso.raise_()
        self.framebtnApagarEquipo = QtWidgets.QFrame(self.frame)
        self.framebtnApagarEquipo.setGeometry(QtCore.QRect(460, 430, 300, 100))
        self.framebtnApagarEquipo.setStyleSheet("#framebtnApagarEquipo{\n"
"background-color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 200);\n"
"border-radius: 10px;\n"
"border: none;\n"
"}")
        self.framebtnApagarEquipo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framebtnApagarEquipo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framebtnApagarEquipo.setObjectName("framebtnApagarEquipo")
        self.lblPresionarApagar = QtWidgets.QLabel(self.framebtnApagarEquipo)
        self.lblPresionarApagar.setGeometry(QtCore.QRect(2, 66, 296, 32))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblPresionarApagar.setFont(font)
        self.lblPresionarApagar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblPresionarApagar.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;")
        self.lblPresionarApagar.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPresionarApagar.setObjectName("lblPresionarApagar")
        self.lblImgApagar = QtWidgets.QLabel(self.framebtnApagarEquipo)
        self.lblImgApagar.setGeometry(QtCore.QRect(70, 15, 35, 35))
        self.lblImgApagar.setStyleSheet("background-color: transparent;")
        self.lblImgApagar.setText("")
        self.lblImgApagar.setScaledContents(True)
        self.lblImgApagar.setObjectName("lblImgApagar")
        self.lblFrmApagar = QtWidgets.QLabel(self.framebtnApagarEquipo)
        self.lblFrmApagar.setGeometry(QtCore.QRect(2, 2, 296, 64))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblFrmApagar.setFont(font)
        self.lblFrmApagar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblFrmApagar.setAutoFillBackground(False)
        self.lblFrmApagar.setStyleSheet("background-color: #FF0000;\n"
"color: rgb(255, 255, 255);\n"
"border: none;\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"padding-left: 30px;")
        self.lblFrmApagar.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFrmApagar.setObjectName("lblFrmApagar")
        self.lblPresionarApagar.raise_()
        self.lblFrmApagar.raise_()
        self.lblImgApagar.raise_()
        self.frameBtnTalloSolo = QtWidgets.QFrame(self.frame)
        self.frameBtnTalloSolo.setGeometry(QtCore.QRect(80, 70, 300, 100))
        self.frameBtnTalloSolo.setStyleSheet("#frameBtnTalloSolo{\n"
"background-color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 200);\n"
"border-radius: 10px;\n"
"border: none;\n"
"}")
        self.frameBtnTalloSolo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBtnTalloSolo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBtnTalloSolo.setObjectName("frameBtnTalloSolo")
        self.lblPresionarTalloSolo = QtWidgets.QLabel(self.frameBtnTalloSolo)
        self.lblPresionarTalloSolo.setGeometry(QtCore.QRect(2, 66, 296, 32))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblPresionarTalloSolo.setFont(font)
        self.lblPresionarTalloSolo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblPresionarTalloSolo.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;")
        self.lblPresionarTalloSolo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPresionarTalloSolo.setObjectName("lblPresionarTalloSolo")
        self.lblImgTalloSolo = QtWidgets.QLabel(self.frameBtnTalloSolo)
        self.lblImgTalloSolo.setGeometry(QtCore.QRect(25, 15, 60, 35))
        self.lblImgTalloSolo.setStyleSheet("background-color: transparent;")
        self.lblImgTalloSolo.setText("")
        self.lblImgTalloSolo.setScaledContents(True)
        self.lblImgTalloSolo.setObjectName("lblImgTalloSolo")
        self.lblTalloSolo = QtWidgets.QLabel(self.frameBtnTalloSolo)
        self.lblTalloSolo.setGeometry(QtCore.QRect(2, 2, 296, 64))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblTalloSolo.setFont(font)
        self.lblTalloSolo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblTalloSolo.setAutoFillBackground(False)
        self.lblTalloSolo.setStyleSheet("background-color: rgb(255, 207, 11);\n"
"color: rgb(0, 0, 0);\n"
"border: none;\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"padding-left: 40px;")
        self.lblTalloSolo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTalloSolo.setObjectName("lblTalloSolo")
        self.lblPresionarTalloSolo.raise_()
        self.lblTalloSolo.raise_()
        self.lblImgTalloSolo.raise_()
        self.frameBtnTalloCoral = QtWidgets.QFrame(self.frame)
        self.frameBtnTalloCoral.setGeometry(QtCore.QRect(460, 70, 300, 100))
        self.frameBtnTalloCoral.setStyleSheet("#frameBtnTalloCoral{\n"
"background-color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 200);\n"
"border-radius: 10px;\n"
"border: none;\n"
"}")
        self.frameBtnTalloCoral.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBtnTalloCoral.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBtnTalloCoral.setObjectName("frameBtnTalloCoral")
        self.lblPresionarTalloCoral = QtWidgets.QLabel(self.frameBtnTalloCoral)
        self.lblPresionarTalloCoral.setGeometry(QtCore.QRect(2, 66, 296, 32))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblPresionarTalloCoral.setFont(font)
        self.lblPresionarTalloCoral.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblPresionarTalloCoral.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;")
        self.lblPresionarTalloCoral.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPresionarTalloCoral.setObjectName("lblPresionarTalloCoral")
        self.lblImgTalloCoral = QtWidgets.QLabel(self.frameBtnTalloCoral)
        self.lblImgTalloCoral.setGeometry(QtCore.QRect(25, 15, 60, 35))
        self.lblImgTalloCoral.setStyleSheet("background-color: transparent;")
        self.lblImgTalloCoral.setText("")
        self.lblImgTalloCoral.setScaledContents(True)
        self.lblImgTalloCoral.setObjectName("lblImgTalloCoral")
        self.lblTalloCoral = QtWidgets.QLabel(self.frameBtnTalloCoral)
        self.lblTalloCoral.setGeometry(QtCore.QRect(2, 2, 296, 64))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblTalloCoral.setFont(font)
        self.lblTalloCoral.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblTalloCoral.setAutoFillBackground(False)
        self.lblTalloCoral.setStyleSheet("background-color: rgb(255, 207, 11);\n"
"color: rgb(0, 0, 0);\n"
"border: none;\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"padding-left: 55px;")
        self.lblTalloCoral.setScaledContents(True)
        self.lblTalloCoral.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTalloCoral.setObjectName("lblTalloCoral")
        self.lblPresionarTalloCoral.raise_()
        self.lblTalloCoral.raise_()
        self.lblImgTalloCoral.raise_()
        self.frameBtnMediaValvaTS = QtWidgets.QFrame(self.frame)
        self.frameBtnMediaValvaTS.setGeometry(QtCore.QRect(840, 70, 300, 100))
        self.frameBtnMediaValvaTS.setStyleSheet("#frameBtnMediaValvaTS{\n"
"background-color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 200);\n"
"border-radius: 10px;\n"
"border: none;\n"
"}")
        self.frameBtnMediaValvaTS.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBtnMediaValvaTS.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBtnMediaValvaTS.setObjectName("frameBtnMediaValvaTS")
        self.lblPresionarMediaValvaTs = QtWidgets.QLabel(self.frameBtnMediaValvaTS)
        self.lblPresionarMediaValvaTs.setGeometry(QtCore.QRect(2, 66, 296, 32))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblPresionarMediaValvaTs.setFont(font)
        self.lblPresionarMediaValvaTs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblPresionarMediaValvaTs.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;")
        self.lblPresionarMediaValvaTs.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPresionarMediaValvaTs.setObjectName("lblPresionarMediaValvaTs")
        self.lblImgMediaValvaTs = QtWidgets.QLabel(self.frameBtnMediaValvaTS)
        self.lblImgMediaValvaTs.setGeometry(QtCore.QRect(30, 15, 35, 35))
        self.lblImgMediaValvaTs.setStyleSheet("background-color: transparent;")
        self.lblImgMediaValvaTs.setText("")
        self.lblImgMediaValvaTs.setScaledContents(True)
        self.lblImgMediaValvaTs.setObjectName("lblImgMediaValvaTs")
        self.lblMediaValvaTs = QtWidgets.QLabel(self.frameBtnMediaValvaTS)
        self.lblMediaValvaTs.setGeometry(QtCore.QRect(2, 2, 296, 64))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblMediaValvaTs.setFont(font)
        self.lblMediaValvaTs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblMediaValvaTs.setAutoFillBackground(False)
        self.lblMediaValvaTs.setStyleSheet("background-color: rgb(255, 207, 11);\n"
"color: rgb(0, 0, 0);\n"
"border: none;\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"padding-left: 50px;")
        self.lblMediaValvaTs.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMediaValvaTs.setObjectName("lblMediaValvaTs")
        self.lblPresionarMediaValvaTs.raise_()
        self.lblMediaValvaTs.raise_()
        self.lblImgMediaValvaTs.raise_()
        self.frameBtnMediaValvaTc = QtWidgets.QFrame(self.frame)
        self.frameBtnMediaValvaTc.setGeometry(QtCore.QRect(270, 220, 300, 100))
        self.frameBtnMediaValvaTc.setStyleSheet("#frameBtnMediaValvaTc{\n"
"background-color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 200);\n"
"border-radius: 10px;\n"
"border: none;\n"
"}")
        self.frameBtnMediaValvaTc.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBtnMediaValvaTc.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBtnMediaValvaTc.setObjectName("frameBtnMediaValvaTc")
        self.lblPresionarMediaValvaTc = QtWidgets.QLabel(self.frameBtnMediaValvaTc)
        self.lblPresionarMediaValvaTc.setGeometry(QtCore.QRect(2, 66, 296, 32))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblPresionarMediaValvaTc.setFont(font)
        self.lblPresionarMediaValvaTc.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblPresionarMediaValvaTc.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;")
        self.lblPresionarMediaValvaTc.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPresionarMediaValvaTc.setObjectName("lblPresionarMediaValvaTc")
        self.lblImgMediaValvaTc = QtWidgets.QLabel(self.frameBtnMediaValvaTc)
        self.lblImgMediaValvaTc.setGeometry(QtCore.QRect(25, 15, 35, 35))
        self.lblImgMediaValvaTc.setStyleSheet("background-color: transparent;")
        self.lblImgMediaValvaTc.setText("")
        self.lblImgMediaValvaTc.setScaledContents(True)
        self.lblImgMediaValvaTc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblImgMediaValvaTc.setObjectName("lblImgMediaValvaTc")
        self.lblMediaValvaTc = QtWidgets.QLabel(self.frameBtnMediaValvaTc)
        self.lblMediaValvaTc.setGeometry(QtCore.QRect(2, 2, 296, 64))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblMediaValvaTc.setFont(font)
        self.lblMediaValvaTc.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblMediaValvaTc.setAutoFillBackground(False)
        self.lblMediaValvaTc.setStyleSheet("background-color: rgb(255, 207, 11);\n"
"color: rgb(0, 0, 0);\n"
"border: none;\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"padding-left: 50px;")
        self.lblMediaValvaTc.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMediaValvaTc.setObjectName("lblMediaValvaTc")
        self.lblPresionarMediaValvaTc.raise_()
        self.lblMediaValvaTc.raise_()
        self.lblImgMediaValvaTc.raise_()
        self.frameBtnOtros = QtWidgets.QFrame(self.frame)
        self.frameBtnOtros.setGeometry(QtCore.QRect(650, 220, 300, 100))
        self.frameBtnOtros.setStyleSheet("#frameBtnOtros{\n"
"background-color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 200);\n"
"border-radius: 10px;\n"
"border: none;\n"
"}")
        self.frameBtnOtros.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBtnOtros.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBtnOtros.setObjectName("frameBtnOtros")
        self.lblPresionarOtros = QtWidgets.QLabel(self.frameBtnOtros)
        self.lblPresionarOtros.setGeometry(QtCore.QRect(2, 66, 296, 32))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblPresionarOtros.setFont(font)
        self.lblPresionarOtros.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblPresionarOtros.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;")
        self.lblPresionarOtros.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPresionarOtros.setObjectName("lblPresionarOtros")
        self.lblImgOtros = QtWidgets.QLabel(self.frameBtnOtros)
        self.lblImgOtros.setGeometry(QtCore.QRect(80, 15, 35, 35))
        self.lblImgOtros.setStyleSheet("background-color: transparent;")
        self.lblImgOtros.setText("")
        self.lblImgOtros.setScaledContents(True)
        self.lblImgOtros.setObjectName("lblImgOtros")
        self.lblOtros = QtWidgets.QLabel(self.frameBtnOtros)
        self.lblOtros.setGeometry(QtCore.QRect(2, 2, 296, 64))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblOtros.setFont(font)
        self.lblOtros.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblOtros.setAutoFillBackground(False)
        self.lblOtros.setStyleSheet("background-color: rgb(255, 207, 11);\n"
"color: rgb(0, 0, 0);\n"
"border: none;\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"padding-left: 30px;")
        self.lblOtros.setAlignment(QtCore.Qt.AlignCenter)
        self.lblOtros.setObjectName("lblOtros")
        self.lblPresionarOtros.raise_()
        self.lblOtros.raise_()
        self.lblImgOtros.raise_()
        self.labelFondoSistema = QtWidgets.QLabel(self.centralwidget)
        self.labelFondoSistema.setGeometry(QtCore.QRect(0, 0, 1600, 900))
        self.labelFondoSistema.setFocusPolicy(QtCore.Qt.NoFocus)
        self.labelFondoSistema.setText("")
        self.labelFondoSistema.setScaledContents(True)
        self.labelFondoSistema.setObjectName("labelFondoSistema")
        self.frameFondoSistema = QtWidgets.QFrame(self.centralwidget)
        self.frameFondoSistema.setGeometry(QtCore.QRect(0, 0, 1600, 900))
        self.frameFondoSistema.setStyleSheet("background-color: rgba(43, 43, 43, 200);\n"
"")
        self.frameFondoSistema.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameFondoSistema.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameFondoSistema.setObjectName("frameFondoSistema")
        self.frmSombra = QtWidgets.QFrame(self.centralwidget)
        self.frmSombra.setGeometry(QtCore.QRect(0, 0, 1600, 900))
        self.frmSombra.setStyleSheet("#frmSombra{\n"
"background-color: rgba(0, 0, 0, 80);\n"
"}")
        self.frmSombra.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmSombra.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmSombra.setObjectName("frmSombra")
        self.frmFinalizarAlerta = QtWidgets.QFrame(self.frmSombra)
        self.frmFinalizarAlerta.setGeometry(QtCore.QRect(450, 297, 700, 305))
        self.frmFinalizarAlerta.setStyleSheet("#frmFinalizarAlerta{background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border:none;\n"
"border-radius: 10px;\n"
"border: 2px solid #D9D9D9;}")
        self.frmFinalizarAlerta.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmFinalizarAlerta.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmFinalizarAlerta.setObjectName("frmFinalizarAlerta")
        self.lblTituloFinalizar = QtWidgets.QLabel(self.frmFinalizarAlerta)
        self.lblTituloFinalizar.setGeometry(QtCore.QRect(2, 2, 696, 50))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lblTituloFinalizar.setFont(font)
        self.lblTituloFinalizar.setStyleSheet("background-color: rgb(29, 71, 131);\n"
"color: rgb(255, 255, 255);\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;")
        self.lblTituloFinalizar.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTituloFinalizar.setObjectName("lblTituloFinalizar")
        self.imgFinalizar = QtWidgets.QLabel(self.frmFinalizarAlerta)
        self.imgFinalizar.setGeometry(QtCore.QRect(100, 80, 100, 100))
        self.imgFinalizar.setText("")
        self.imgFinalizar.setScaledContents(True)
        self.imgFinalizar.setObjectName("imgFinalizar")
        self.lblTextoFinalizar = QtWidgets.QLabel(self.frmFinalizarAlerta)
        self.lblTextoFinalizar.setGeometry(QtCore.QRect(200, 105, 400, 50))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblTextoFinalizar.setFont(font)
        self.lblTextoFinalizar.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTextoFinalizar.setObjectName("lblTextoFinalizar")
        self.frmBtnApagar = QtWidgets.QFrame(self.frmFinalizarAlerta)
        self.frmBtnApagar.setGeometry(QtCore.QRect(30, 210, 200, 70))
        self.frmBtnApagar.setStyleSheet("#frmBtnApagar{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid #bbbbbb;\n"
"}")
        self.frmBtnApagar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmBtnApagar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmBtnApagar.setObjectName("frmBtnApagar")
        self.lblPresione1Apagar = QtWidgets.QLabel(self.frmBtnApagar)
        self.lblPresione1Apagar.setGeometry(QtCore.QRect(0, 40, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblPresione1Apagar.setFont(font)
        self.lblPresione1Apagar.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPresione1Apagar.setObjectName("lblPresione1Apagar")
        self.lblApagar = QtWidgets.QLabel(self.frmBtnApagar)
        self.lblApagar.setGeometry(QtCore.QRect(2, 2, 196, 38))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblApagar.setFont(font)
        self.lblApagar.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"background-color: rgb(85, 170, 0);")
        self.lblApagar.setAlignment(QtCore.Qt.AlignCenter)
        self.lblApagar.setObjectName("lblApagar")
        self.frmBtnReiniciar = QtWidgets.QFrame(self.frmFinalizarAlerta)
        self.frmBtnReiniciar.setGeometry(QtCore.QRect(250, 210, 200, 70))
        self.frmBtnReiniciar.setStyleSheet("#frmBtnReiniciar{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid #bbbbbb;\n"
"}")
        self.frmBtnReiniciar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmBtnReiniciar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmBtnReiniciar.setObjectName("frmBtnReiniciar")
        self.lblPresione2Apagar = QtWidgets.QLabel(self.frmBtnReiniciar)
        self.lblPresione2Apagar.setGeometry(QtCore.QRect(0, 40, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblPresione2Apagar.setFont(font)
        self.lblPresione2Apagar.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPresione2Apagar.setObjectName("lblPresione2Apagar")
        self.lblReiniciar = QtWidgets.QLabel(self.frmBtnReiniciar)
        self.lblReiniciar.setGeometry(QtCore.QRect(2, 2, 196, 38))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblReiniciar.setFont(font)
        self.lblReiniciar.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"background-color: #0055FF;")
        self.lblReiniciar.setAlignment(QtCore.Qt.AlignCenter)
        self.lblReiniciar.setObjectName("lblReiniciar")
        self.frmBtnApagarCancelar = QtWidgets.QFrame(self.frmFinalizarAlerta)
        self.frmBtnApagarCancelar.setGeometry(QtCore.QRect(470, 210, 200, 70))
        self.frmBtnApagarCancelar.setStyleSheet("#frmBtnApagarCancelar{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid #bbbbbb;\n"
"}")
        self.frmBtnApagarCancelar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmBtnApagarCancelar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmBtnApagarCancelar.setObjectName("frmBtnApagarCancelar")
        self.lblPresione3Apagar = QtWidgets.QLabel(self.frmBtnApagarCancelar)
        self.lblPresione3Apagar.setGeometry(QtCore.QRect(0, 40, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblPresione3Apagar.setFont(font)
        self.lblPresione3Apagar.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPresione3Apagar.setObjectName("lblPresione3Apagar")
        self.lblCancelarApagar = QtWidgets.QLabel(self.frmBtnApagarCancelar)
        self.lblCancelarApagar.setGeometry(QtCore.QRect(2, 2, 196, 38))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblCancelarApagar.setFont(font)
        self.lblCancelarApagar.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"background-color: rgb(255, 0, 0);")
        self.lblCancelarApagar.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCancelarApagar.setObjectName("lblCancelarApagar")
        self.labelFondoSistema.raise_()
        self.frameFondoSistema.raise_()
        self.frame.raise_()
        self.frmSombra.raise_()
        Modal_Inicio.setCentralWidget(self.centralwidget)

        self.retranslateUi(Modal_Inicio)
        QtCore.QMetaObject.connectSlotsByName(Modal_Inicio)

    def retranslateUi(self, Modal_Inicio):
        _translate = QtCore.QCoreApplication.translate
        Modal_Inicio.setWindowTitle(_translate("Modal_Inicio", "MainWindow"))
        self.lblPresionarReestablecer.setText(_translate("Modal_Inicio", "PRESIONE (-)"))
        self.lblReestablecer.setText(_translate("Modal_Inicio", "REESTABLECER"))
        self.lblPresionarIniciarProceso.setText(_translate("Modal_Inicio", "PRESIONE  (↵)"))
        self.lblIniciarProceso.setText(_translate("Modal_Inicio", "INICIAR PROCESO"))
        self.lblPresionarApagar.setText(_translate("Modal_Inicio", "PRESIONE (0)"))
        self.lblFrmApagar.setText(_translate("Modal_Inicio", "APAGAR"))
        self.lblPresionarTalloSolo.setText(_translate("Modal_Inicio", "PRESIONE (1)"))
        self.lblTalloSolo.setText(_translate("Modal_Inicio", "TALLO SOLO"))
        self.lblPresionarTalloCoral.setText(_translate("Modal_Inicio", "PRESIONE (2)"))
        self.lblTalloCoral.setText(_translate("Modal_Inicio", "TALLO CORAL"))
        self.lblPresionarMediaValvaTs.setText(_translate("Modal_Inicio", "PRESIONE (3)"))
        self.lblMediaValvaTs.setText(_translate("Modal_Inicio", "MEDIA VALVA T/S"))
        self.lblPresionarMediaValvaTc.setText(_translate("Modal_Inicio", "PRESIONE (4)"))
        self.lblMediaValvaTc.setText(_translate("Modal_Inicio", "MEDIA VALVA T/C"))
        self.lblPresionarOtros.setText(_translate("Modal_Inicio", "PRESIONE (5)"))
        self.lblOtros.setText(_translate("Modal_Inicio", "OTROS"))
        self.lblTituloFinalizar.setText(_translate("Modal_Inicio", ".::: APAGAR EQUIPO :::."))
        self.lblTextoFinalizar.setText(_translate("Modal_Inicio", "¿QUE OPERACIÓN DESEA REALIZAR?"))
        self.lblPresione1Apagar.setText(_translate("Modal_Inicio", ".::: PRESIONE 1 :::."))
        self.lblApagar.setText(_translate("Modal_Inicio", "APAGAR"))
        self.lblPresione2Apagar.setText(_translate("Modal_Inicio", ".::: PRESIONE 2 :::."))
        self.lblReiniciar.setText(_translate("Modal_Inicio", "REINICIAR"))
        self.lblPresione3Apagar.setText(_translate("Modal_Inicio", ".::: PRESIONE 3 :::."))
        self.lblCancelarApagar.setText(_translate("Modal_Inicio", "CANCELAR"))
